check for existance of check_procs script

diff --git a/safe-reboot b/safe-reboot
--- a/safe-reboot
+++ b/safe-reboot
@@ -5,6 +5,11 @@ if [ "`whoami`" != "root" ]; then
 	exit
 fi
 
+if [ ! -f /usr/lib/nagios/plugins/check_procs ]; then
+	echo "/usr/lib/nagios/plugins/check_procs not found, unable to check for running updates"
+	exit 2
+fi
+
 ERROR=0
 /usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C apt &> /dev/null || ERROR=1
 /usr/lib/nagios/plugins/check_procs -w 0 -c 1 -C apt-get &> /dev/null || ERROR=1
